// Generated by scripts/generate-demo-audio.ps1. Edit docs/demos/scenarios.fr.json.
export type DemoSectorId = 'garage' | 'controle-technique'
export interface DemoScenario {
  id: DemoSectorId
  label: string
  audioSrc: string
  durationSeconds: number
  cues: { speaker: 'sparra' | 'client'; text: string; startSeconds: number; endSeconds: number }[]
  receipt: { status: string; contact: string; phone: string; summary: string; nextAction: string }
}
export const demoScenarios: DemoScenario[] =[
  {
    "id": "garage",
    "label": "Garage",
    "audioSrc": "/demos/garage-revision.mp3",
    "durationSeconds": 36.356917,
    "cues": [
      {
        "speaker": "sparra",
        "text": "Bonjour, vous êtes au Garage Horizon. Je suis Sparra, un agent IA. Quelle est votre demande ?",
        "startSeconds": 0.0,
        "endSeconds": 7.522625
      },
      {
        "speaker": "client",
        "text": "Bonjour, je voudrais faire une révision de ma voiture.",
        "startSeconds": 7.872625,
        "endSeconds": 11.650333
      },
      {
        "speaker": "sparra",
        "text": "Je peux recueillir votre demande pour l'équipe. Quand préférez-vous être rappelé ?",
        "startSeconds": 12.000333,
        "endSeconds": 17.467791
      },
      {
        "speaker": "client",
        "text": "Demain matin, si possible. Je m'appelle Camille. Pour cet exemple, mon numéro est fictif.",
        "startSeconds": 17.817791,
        "endSeconds": 25.385041
      },
      {
        "speaker": "sparra",
        "text": "D'accord, votre préférence est un rappel demain matin pour une révision. L'équipe devra confirmer le rappel et les modalités. Aucun rendez-vous n'est confirmé.",
        "startSeconds": 25.735041,
        "endSeconds": 36.356916
      }
    ],
    "receipt": {
      "status": "Demande à traiter",
      "contact": "Camille — personne fictive",
      "phone": "Numéro fictif, non composé",
      "summary": "Demande de révision au Garage Horizon. Préférence de rappel : demain matin.",
      "nextAction": "Rappeler Camille et confirmer les modalités avec l’équipe. Aucun rendez-vous confirmé."
    }
  },
  {
    "id": "controle-technique",
    "label": "Contrôle technique",
    "audioSrc": "/demos/controle-technique.mp3",
    "durationSeconds": 39.798458,
    "cues": [
      {
        "speaker": "sparra",
        "text": "Bonjour, vous êtes au Centre Clair. Je suis Sparra, un agent IA. Quelle est votre demande ?",
        "startSeconds": 0.0,
        "endSeconds": 7.51775
      },
      {
        "speaker": "client",
        "text": "Bonjour, je souhaite une visite de contrôle technique pour ma voiture.",
        "startSeconds": 7.86775,
        "endSeconds": 12.391083
      },
      {
        "speaker": "sparra",
        "text": "Quelle est votre préférence pour cette visite ? L'équipe devra vérifier les disponibilités.",
        "startSeconds": 12.741083,
        "endSeconds": 19.043375
      },
      {
        "speaker": "client",
        "text": "Plutôt vendredi après-midi. Je m'appelle Alex. Pour cet exemple, mon numéro est fictif.",
        "startSeconds": 19.393375,
        "endSeconds": 26.674375
      },
      {
        "speaker": "sparra",
        "text": "Je retiens une demande de contrôle technique, avec une préférence pour vendredi après-midi. La date, le tarif et les modalités restent à confirmer avec l'équipe. Aucun rendez-vous n'est réservé.",
        "startSeconds": 27.024375,
        "endSeconds": 39.798458
      }
    ],
    "receipt": {
      "status": "Visite à confirmer",
      "contact": "Alex — personne fictive",
      "phone": "Numéro fictif, non composé",
      "summary": "Demande de visite de contrôle technique au Centre Clair. Préférence : vendredi après-midi.",
      "nextAction": "Contacter Alex pour confirmer les disponibilités et les modalités. Aucun rendez-vous réservé."
    }
  }
]
