// Generated by scripts/generate-demo-audio.ps1. Edit docs/demos/scenarios.fr.json.
export type DemoSectorId = 'garage' | 'controle-technique'
export interface DemoScenario {
  id: DemoSectorId
  label: string
  audioSrc: string
  durationSeconds: number
  cues: { speaker: 'sparra' | 'client'; text: string; startSeconds: number; endSeconds: number }[]
  receipt: { status: string; contact: string; phone: string; summary: string; nextAction: string }
}
export const demoScenarios: DemoScenario[] =[
  {
    "id": "garage",
    "label": "Garage",
    "audioSrc": "/demos/garage-revision.mp3",
    "durationSeconds": 30.344,
    "cues": [
      {
        "speaker": "sparra",
        "text": "Bonjour, vous êtes au Garage Horizon. Je suis Sparra, un agent IA. Quelle est votre demande ?",
        "startSeconds": 0.0,
        "endSeconds": 5.88
      },
      {
        "speaker": "client",
        "text": "Bonjour, je voudrais faire une révision de ma voiture.",
        "startSeconds": 6.23,
        "endSeconds": 9.47
      },
      {
        "speaker": "sparra",
        "text": "Je peux recueillir votre demande pour l'équipe. Quand préférez-vous être rappelé ?",
        "startSeconds": 9.82,
        "endSeconds": 14.356
      },
      {
        "speaker": "client",
        "text": "Demain matin, si possible. Je m'appelle Camille. Pour cet exemple, mon numéro est fictif.",
        "startSeconds": 14.706,
        "endSeconds": 21.066
      },
      {
        "speaker": "sparra",
        "text": "D'accord, votre préférence est un rappel demain matin pour une révision. L'équipe devra confirmer le rappel et les modalités. Aucun rendez-vous n'est confirmé.",
        "startSeconds": 21.416,
        "endSeconds": 30.344
      }
    ],
    "receipt": {
      "status": "Demande à traiter",
      "contact": "Camille — personne fictive",
      "phone": "Numéro fictif, non composé",
      "summary": "Demande de révision au Garage Horizon. Préférence de rappel : demain matin.",
      "nextAction": "Rappeler Camille et confirmer les modalités avec l’équipe. Aucun rendez-vous confirmé."
    }
  },
  {
    "id": "controle-technique",
    "label": "Contrôle technique",
    "audioSrc": "/demos/controle-technique.mp3",
    "durationSeconds": 33.224,
    "cues": [
      {
        "speaker": "sparra",
        "text": "Bonjour, vous êtes au Centre Clair. Je suis Sparra, un agent IA. Quelle est votre demande ?",
        "startSeconds": 0.0,
        "endSeconds": 5.4
      },
      {
        "speaker": "client",
        "text": "Bonjour, je souhaite une visite de contrôle technique pour ma voiture.",
        "startSeconds": 5.75,
        "endSeconds": 9.638
      },
      {
        "speaker": "sparra",
        "text": "Quelle est votre préférence pour cette visite ? L'équipe devra vérifier les disponibilités.",
        "startSeconds": 9.988,
        "endSeconds": 15.388
      },
      {
        "speaker": "client",
        "text": "Plutôt vendredi après-midi. Je m'appelle Alex. Pour cet exemple, mon numéro est fictif.",
        "startSeconds": 15.738,
        "endSeconds": 21.618
      },
      {
        "speaker": "sparra",
        "text": "Je retiens une demande de contrôle technique, avec une préférence pour vendredi après-midi. La date, le tarif et les modalités restent à confirmer avec l'équipe. Aucun rendez-vous n'est réservé.",
        "startSeconds": 21.968,
        "endSeconds": 33.224
      }
    ],
    "receipt": {
      "status": "Visite à confirmer",
      "contact": "Alex — personne fictive",
      "phone": "Numéro fictif, non composé",
      "summary": "Demande de visite de contrôle technique au Centre Clair. Préférence : vendredi après-midi.",
      "nextAction": "Contacter Alex pour confirmer les disponibilités et les modalités. Aucun rendez-vous réservé."
    }
  }
]
