export const activityMessages = {
  fr: {
    title: 'Mon activité', description: 'Donnez à Sparra les informations utiles pour accueillir vos appelants.', establishment: 'Votre établissement', answerInformation: 'Informations pour répondre', callHandling: 'Gestion des appels', requiredHint: 'Le nom et le secteur sont obligatoires.',
    businessName: 'Nom de l’établissement', businessNameHint: 'Le nom que Sparra utilise pour accueillir vos appelants.', businessNamePlaceholder: 'Ex. : Garage Martin', sector: 'Secteur', sectorHint: 'Choisissez le métier de votre établissement.', garage: 'Garage', controleTechnique: 'Contrôle technique',
    openingHours: 'Horaires', services: 'Prestations', prices: 'Tarifs', faq: 'Questions fréquentes', instructions: 'Consignes de réponse', knowledgeHint: 'Ces informations sont facultatives. Commencez par vos horaires et vos prestations. Une information laissée vide reste inconnue de Sparra. Les exemples ne sont pas enregistrés.',
    fieldHints: { openingHours: 'Jours et heures d’ouverture, pauses et fermetures exceptionnelles.', services: 'Les prestations proposées et celles que vous ne réalisez pas.', prices: 'Les montants, ce qu’ils comprennent et les cas où un devis est nécessaire.', faq: 'Les questions habituelles de vos clients et vos réponses.', instructions: 'Comment accueillir les demandes et ce que votre équipe doit confirmer. Ces consignes n’activent pas la réservation de rendez-vous.' },
    fieldExamples: { openingHours: 'Ex. : Du lundi au vendredi, 8 h–12 h et 14 h–18 h. Fermé le samedi.', services: 'Ex. : Entretien, vidange et pneumatiques. Pas de travaux de carrosserie.', prices: 'Ex. : Diagnostic à partir de 60 €. Réparations sur devis après examen du véhicule.', faq: 'Ex. : Faut-il apporter la carte grise ? Oui, pour toute intervention.', instructions: 'Ex. : Pour un rendez-vous, recueillir la demande et le numéro de rappel. L’équipe confirme ensuite la disponibilité.' },
    inspectionExamples: { openingHours: 'Ex. : Du lundi au vendredi, 8 h–12 h et 14 h–18 h. Fermé le samedi.', services: 'Ex. : Contrôle technique des véhicules légers et contre-visite. Pas de réparations.', prices: 'Ex. : Contrôle technique à 80 €. Préciser le tarif de la contre-visite.', faq: 'Ex. : Quels documents apporter ? La carte grise du véhicule.', instructions: 'Ex. : Recueillir le type de véhicule et le numéro de rappel. L’équipe confirme ensuite le créneau demandé.' },
    characterLimit: 'caractères maximum', transferDestination: 'Numéro de transfert (facultatif)', transferHint: 'Numéro mémorisé uniquement : aucun appel n’y est transféré sur ce pilote. Sparra peut recueillir un message.', transferFormat: 'Utilisez l’indicatif pays, sans espace.', transferPlaceholder: 'Ex. : +33123456789',
    recordingEnabled: 'Conserver l’audio des prochains appels pendant 30 jours', recordingHint: 'Ce réglage s’applique aux prochains appels. Les appelants peuvent refuser l’enregistrement. Les transcriptions sont conservées 30 jours.', recordingUnavailable: 'L’enregistrement audio n’est pas disponible pour votre entreprise. Vous pouvez désactiver un réglage déjà enregistré.', recordingLegacy: 'Un ancien réglage audio est enregistré. Corrigez-le explicitement avant d’enregistrer votre configuration.', recordingCorrectLegacy: 'Utiliser les réglages d’enregistrement local', recordingDeactivation: 'Désactivation pour les prochains appels à enregistrer. Les enregistrements existants conservent leur échéance.', recordingContactPhone: 'Téléphone de contact (facultatif)', recordingContactHint: 'Contact facultatif de votre entreprise. Format international, sans espace.', recordingContactPlaceholder: 'Ex. : +33123456789',
    fieldErrors: { required: 'Renseignez le nom de votre établissement.', nameTooLong: 'Limitez le nom à 80 caractères.', tooLong: 'Limitez ce texte à', phoneFormat: 'Utilisez l’indicatif pays sans espace, par exemple +33123456789.' }, localInvalid: 'Corrigez les champs signalés avant d’enregistrer.',
    save: 'Enregistrer', saveHint: 'Les informations enregistrées s’appliquent aux prochains appels pris en charge. Enregistrer n’active pas votre ligne téléphonique.', unsaved: 'Modifications non enregistrées.', upToDate: 'Aucune modification en attente.', ensuring: 'Création de votre espace…', checking: 'Vérification des informations enregistrées…', saving: 'Enregistrement…', stopWaiting: 'Arrêter d’attendre', saveWaitHint: 'L’enregistrement peut encore aboutir si vous arrêtez d’attendre.', saved: 'Configuration enregistrée.', outcomeUnknown: 'Le résultat de l’enregistrement est inconnu. Vérifiez la dernière version avant d’enregistrer à nouveau.', noSavedConfiguration: 'Aucune configuration enregistrée.', latestMatches: 'Votre saisie correspond aux informations enregistrées.', latestDiffers: 'Les informations enregistrées sont différentes de votre saisie.', replaceWarning: 'Remplacer le brouillon abandonnera vos modifications locales.', conflict: 'La configuration a changé. Vérifiez la dernière version avant de remplacer votre brouillon.', invalid: 'Certaines informations n’ont pas pu être enregistrées. Vérifiez les champs puis réessayez.', unavailable: 'Informations indisponibles. Réessayez ou rechargez la page.',
  },
  en: {
    title: 'My business', description: 'Give Sparra the information it needs to welcome your callers.', establishment: 'Your business', answerInformation: 'Information for answering', callHandling: 'Call handling', requiredHint: 'Business name and sector are required.',
    businessName: 'Business name', businessNameHint: 'The name Sparra uses to welcome your callers.', businessNamePlaceholder: 'E.g. Martin’s Garage', sector: 'Sector', sectorHint: 'Choose your business’s trade.', garage: 'Garage', controleTechnique: 'Vehicle inspection',
    openingHours: 'Opening hours', services: 'Services', prices: 'Prices', faq: 'Frequently asked questions', instructions: 'Response instructions', knowledgeHint: 'This information is optional. Start with opening hours and services. Information left blank stays unknown to Sparra. Examples are not saved.',
    fieldHints: { openingHours: 'Opening days and times, breaks and exceptional closures.', services: 'The services you offer and the work you do not carry out.', prices: 'Amounts, what they include and when a quote is needed.', faq: 'Your customers’ usual questions and your answers.', instructions: 'How to handle requests and what your team must confirm. These instructions do not enable appointment booking.' },
    fieldExamples: { openingHours: 'E.g. Monday to Friday, 8 am–12 pm and 2 pm–6 pm. Closed on Saturdays.', services: 'E.g. Servicing, oil changes and tyres. No bodywork repairs.', prices: 'E.g. Diagnostics from €60. Repairs quoted after inspecting the vehicle.', faq: 'E.g. Do I need to bring the vehicle papers? Yes, for any work.', instructions: 'E.g. For an appointment, collect the request and callback number. The team then confirms availability.' },
    inspectionExamples: { openingHours: 'E.g. Monday to Friday, 8 am–12 pm and 2 pm–6 pm. Closed on Saturdays.', services: 'E.g. Vehicle inspections and retests for light vehicles. No repairs.', prices: 'E.g. Vehicle inspection: €80. Specify the retest price.', faq: 'E.g. Which documents should I bring? The vehicle’s registration papers.', instructions: 'E.g. Collect the vehicle type and callback number. The team then confirms the requested appointment time.' },
    characterLimit: 'characters maximum', transferDestination: 'Transfer number (optional)', transferHint: 'Number stored for reference only: no calls are transferred to it in this pilot. Sparra can take a message.', transferFormat: 'Use the country code, without spaces.', transferPlaceholder: 'E.g. +33123456789',
    recordingEnabled: 'Keep audio from future calls for 30 days', recordingHint: 'This setting applies to future calls. Callers can refuse recording. Call transcripts are kept for 30 days.', recordingUnavailable: 'Audio recording is unavailable for your business. You can turn off a previously saved setting.', recordingLegacy: 'An old audio setting is saved. Correct it explicitly before saving your configuration.', recordingCorrectLegacy: 'Use local recording settings', recordingDeactivation: 'Audio will be turned off for future calls when saved. Existing recordings keep their original expiry.', recordingContactPhone: 'Recording contact phone (optional)', recordingContactHint: 'Optional business contact. Use the country code, without spaces.', recordingContactPlaceholder: 'E.g. +33123456789',
    fieldErrors: { required: 'Enter your business name.', nameTooLong: 'Keep the name within 80 characters.', tooLong: 'Keep this text within', phoneFormat: 'Use the country code without spaces, for example +33123456789.' }, localInvalid: 'Correct the highlighted fields before saving.',
    save: 'Save', saveHint: 'Saved information applies to future calls handled by Sparra. Saving does not activate your phone line.', unsaved: 'Unsaved changes.', upToDate: 'No unsaved changes.', ensuring: 'Creating your workspace…', checking: 'Checking saved information…', saving: 'Saving…', stopWaiting: 'Stop waiting', saveWaitHint: 'Saving may still complete if you stop waiting.', saved: 'Configuration saved.', outcomeUnknown: 'The save outcome is unknown. Check the latest version before saving again.', noSavedConfiguration: 'No saved configuration.', latestMatches: 'Your draft matches the saved information.', latestDiffers: 'The saved information is different from your draft.', replaceWarning: 'Replacing your draft will discard your local changes.', conflict: 'The configuration changed. Check the latest version before replacing your draft.', invalid: 'Some information could not be saved. Check the fields and try again.', unavailable: 'Information unavailable. Try again or reload the page.',
  },
}

export const appMessages = {
  fr: { inbox:'Boîte d’appels', business:'Entreprise', account:'Compte', workspace:'Espace', pilot:'Pilote privé', loading:'Chargement…', unavailable:'Données indisponibles. Rechargez la page ou reconnectez-vous.', login:'Aller à la connexion', configure:'Configurez votre entreprise pour préparer l’accueil de vos appels.', noCalls:'Aucun appel pour le moment.', create:'Créer mon espace', createHint:'Créez votre espace pour enregistrer les informations de votre entreprise.', more:'Afficher les appels suivants', refresh:'Actualiser les appels', pending:'Action en cours…', version:'Version enregistrée', latest:'Dernière version enregistrée', checkLatest:'Vérifier la dernière version', loadLatest:'Remplacer le brouillon par la dernière version', details:'Détail de l’appel', partial:'Résumé partiel', summaryUnavailable:'Résumé indisponible', transcript:'Conversation', transcriptUnavailable:'Transcription indisponible', transcriptPartial:'Transcription partielle', unavailableTurns:'tours indisponibles',lostTurns:'tours capturés perdus', moreTurns:'La transcription affichée est limitée aux 200 premiers tours.', snapshot:'Informations connues lors de l’appel', noSnapshot:'Configuration non associée à cet appel.', nextAction:'À faire', contact:'Contact', unconfirmed:'Demande et numéro non confirmés.', caller:'Appelant', assistant:'Sparra', interrupted:'Interrompu', treat:'Marquer comme traité', treated:'Traité', erase:'Effacer cet appel', confirmErase:'Confirmer l’effacement', cancel:'Annuler', eraseWarning:'Le contenu de cet appel sera retiré de votre espace. Les autres copies seront à supprimer.', queued:'Effacement en attente. Les autres copies restent à supprimer.', completed:'Effacement terminé.', admitted:'Reçu le', ended:'Fin détectée', noEnd:'Fin non observée', status:{pending:'En attente',active:'En cours',closing:'Clôture en cours',closed:'Clos',failed:'Échec technique'} },
  en: { inbox:'Call inbox', business:'Business', account:'Account', workspace:'Workspace', pilot:'Private pilot', loading:'Loading…', unavailable:'Data unavailable. Reload the page or sign in again.', login:'Go to sign in', configure:'Configure your business to prepare for your calls.', noCalls:'No calls yet.', create:'Create my workspace', createHint:'Create your workspace to save your business information.', more:'Show more calls', refresh:'Refresh calls', pending:'Working…', version:'Saved version', latest:'Latest saved version', checkLatest:'Check latest version', loadLatest:'Replace draft with latest version', details:'Call details', partial:'Partial summary', summaryUnavailable:'Summary unavailable', transcript:'Conversation', transcriptUnavailable:'Transcript unavailable', transcriptPartial:'Partial transcript', unavailableTurns:'unavailable turns',lostTurns:'captured turns lost', moreTurns:'The displayed transcript is limited to the first 200 turns.', snapshot:'Information known during the call', noSnapshot:'No configuration is associated with this call.', nextAction:'Next action', contact:'Contact', unconfirmed:'Request and number are unconfirmed.', caller:'Caller', assistant:'Sparra', interrupted:'Interrupted', treat:'Mark as treated', treated:'Treated', erase:'Erase this call', confirmErase:'Confirm erasure', cancel:'Cancel', eraseWarning:'This call content will be removed from your workspace. Other copies will need deletion.', queued:'Erasure queued. Other copies are awaiting deletion.', completed:'Erasure completed.', admitted:'Received', ended:'End detected', noEnd:'End not observed', status:{pending:'Pending',active:'Active',closing:'Closing',closed:'Closed',failed:'Technical failure'} },
} as const

export const requestMessages = {
  fr: {
    reason:'Motif', numberSource:'Origine du numéro',
    category:{callback:'Demande de rappel',information:'Demande d’information',appointment_to_confirm:'Rendez-vous à confirmer',declared_urgent:'Urgence déclarée'},
    callbackSource:{caller:'Numéro déclaré par l’appelant',provider:'Numéro fourni par le fournisseur téléphonique',missing:'Aucun numéro disponible'},
  },
  en: {
    reason:'Reason', numberSource:'Number source',
    category:{callback:'Callback request',information:'Information request',appointment_to_confirm:'Appointment to confirm',declared_urgent:'Declared urgent request'},
    callbackSource:{caller:'Number stated by the caller',provider:'Number supplied by the phone provider',missing:'No number available'},
  },
} as const
