export const activityMessages = {
  fr: { title: 'Mon activité', businessName: 'Nom de l’activité', sector: 'Secteur', garage: 'Garage', controleTechnique: 'Contrôle technique', openingHours: 'Horaires', services: 'Services', prices: 'Tarifs', faq: 'Questions fréquentes', instructions: 'Consignes', transferDestination: 'Numéro de transfert', transferHint: 'Le transfert reste désactivé tant que le numéro n’est pas qualifié.', recordingEnabled: 'Conserver l’audio des prochains appels pendant 30 jours', recordingHint: 'Ce choix s’applique après enregistrement aux futurs appels. L’audio est traité par Telnyx. Si activé, l’accueil des appels attend la disponibilité du service audio.', save: 'Enregistrer', saving: 'Enregistrement…', saved: 'Configuration enregistrée.', outcomeUnknown: 'Le résultat de l’enregistrement est inconnu. Vérifiez la dernière version avant d’enregistrer à nouveau.', noSavedConfiguration: 'Aucune configuration enregistrée.', conflict: 'La configuration a changé. Rechargez avant d’enregistrer.', invalid: 'Vérifiez les champs de la configuration.', unavailable: 'Configuration indisponible.' },
  en: { title: 'My business', businessName: 'Business name', sector: 'Sector', garage: 'Garage', controleTechnique: 'Vehicle inspection', openingHours: 'Opening hours', services: 'Services', prices: 'Prices', faq: 'Frequently asked questions', instructions: 'Instructions', transferDestination: 'Transfer number', transferHint: 'Transfer stays disabled until the destination is qualified.', recordingEnabled: 'Keep audio from future calls for 30 days', recordingHint: 'This choice applies after saving to future calls. Audio is processed by Telnyx. When enabled, call handling awaits availability of the audio service.', save: 'Save', saving: 'Saving…', saved: 'Configuration saved.', outcomeUnknown: 'The save outcome is unknown. Check the latest version before saving again.', noSavedConfiguration: 'No saved configuration.', conflict: 'The configuration changed. Reload before saving.', invalid: 'Check the configuration fields.', unavailable: 'Configuration unavailable.' },
}

export const appMessages = {
  fr: { inbox:'Boîte d’appels', business:'Entreprise', account:'Compte', workspace:'Espace', pilot:'Pilote privé', loading:'Chargement…', unavailable:'Données indisponibles. Rechargez la page ou reconnectez-vous.', login:'Aller à la connexion', configure:'Configurez votre entreprise pour préparer l’accueil de vos appels.', noCalls:'Aucun appel pour le moment.', create:'Créer mon espace', createHint:'Créez votre espace pour enregistrer les informations de votre entreprise.', more:'Afficher les appels suivants', pending:'Action en cours…', version:'Version enregistrée', latest:'Dernière version enregistrée', checkLatest:'Vérifier la dernière version', loadLatest:'Remplacer le brouillon par la dernière version', details:'Détail de l’appel', partial:'Résumé partiel', summaryUnavailable:'Résumé indisponible', transcript:'Conversation', transcriptUnavailable:'Transcription indisponible', transcriptPartial:'Transcription partielle', unavailableTurns:'tours indisponibles',lostTurns:'tours capturés perdus', moreTurns:'La transcription affichée est limitée aux 200 premiers tours.', snapshot:'Informations connues lors de l’appel', noSnapshot:'Configuration non associée à cet appel.', nextAction:'À faire', contact:'Contact', unconfirmed:'Demande et numéro non confirmés.', caller:'Appelant', assistant:'Sparra', interrupted:'Interrompu', treat:'Marquer comme traité', treated:'Traité', erase:'Effacer cet appel', confirmErase:'Confirmer l’effacement', cancel:'Annuler', eraseWarning:'Le contenu de cet appel sera retiré de votre espace. Les autres copies seront à supprimer.', queued:'Effacement en attente. Les autres copies restent à supprimer.', completed:'Effacement terminé.', admitted:'Reçu le', ended:'Fin détectée', noEnd:'Fin non observée', status:{pending:'En attente',active:'En cours',closing:'Clôture en cours',closed:'Clos',failed:'Échec technique'} },
  en: { inbox:'Call inbox', business:'Business', account:'Account', workspace:'Workspace', pilot:'Private pilot', loading:'Loading…', unavailable:'Data unavailable. Reload the page or sign in again.', login:'Go to sign in', configure:'Configure your business to prepare for your calls.', noCalls:'No calls yet.', create:'Create my workspace', createHint:'Create your workspace to save your business information.', more:'Show more calls', pending:'Working…', version:'Saved version', latest:'Latest saved version', checkLatest:'Check latest version', loadLatest:'Replace draft with latest version', details:'Call details', partial:'Partial summary', summaryUnavailable:'Summary unavailable', transcript:'Conversation', transcriptUnavailable:'Transcript unavailable', transcriptPartial:'Partial transcript', unavailableTurns:'unavailable turns',lostTurns:'captured turns lost', moreTurns:'The displayed transcript is limited to the first 200 turns.', snapshot:'Information known during the call', noSnapshot:'No configuration is associated with this call.', nextAction:'Next action', contact:'Contact', unconfirmed:'Request and number are unconfirmed.', caller:'Caller', assistant:'Sparra', interrupted:'Interrupted', treat:'Mark as treated', treated:'Treated', erase:'Erase this call', confirmErase:'Confirm erasure', cancel:'Cancel', eraseWarning:'This call content will be removed from your workspace. Other copies will need deletion.', queued:'Erasure queued. Other copies are awaiting deletion.', completed:'Erasure completed.', admitted:'Received', ended:'End detected', noEnd:'End not observed', status:{pending:'Pending',active:'Active',closing:'Closing',closed:'Closed',failed:'Technical failure'} },
} as const

export const requestMessages = {
  fr: {
    reason:'Motif', numberSource:'Origine du numéro',
    category:{callback:'Demande de rappel',information:'Demande d’information',appointment_to_confirm:'Rendez-vous à confirmer',declared_urgent:'Urgence déclarée'},
    callbackSource:{caller:'Numéro déclaré par l’appelant',provider:'Numéro fourni par le fournisseur téléphonique',missing:'Aucun numéro disponible'},
  },
  en: {
    reason:'Reason', numberSource:'Number source',
    category:{callback:'Callback request',information:'Information request',appointment_to_confirm:'Appointment to confirm',declared_urgent:'Declared urgent request'},
    callbackSource:{caller:'Number stated by the caller',provider:'Number supplied by the phone provider',missing:'No number available'},
  },
} as const
