/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as HealthLiveRouteImport } from './routes/health.live'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as AuthMagicConfirmRouteImport } from './routes/auth.magic.confirm'
import { Route as AuthMagicConsumeRouteImport } from './routes/auth.magic.consume'
import { Route as AuthMagicEnrollRouteImport } from './routes/auth.magic.enroll'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api.auth.callback.google'
import { Route as ApiAuthAccountGoogleCallbackRouteImport } from './routes/api.auth.account.google.callback'
import { Route as ApiAuthFirstPasskeyGoogleCallbackRouteImport } from './routes/api.auth.first-passkey.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicConfirmRoute = AuthMagicConfirmRouteImport.update({
  id: '/auth/magic/confirm',
  path: '/auth/magic/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicConsumeRoute = AuthMagicConsumeRouteImport.update({
  id: '/auth/magic/consume',
  path: '/auth/magic/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicEnrollRoute = AuthMagicEnrollRouteImport.update({
  id: '/auth/magic/enroll',
  path: '/auth/magic/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAccountGoogleCallbackRoute =
  ApiAuthAccountGoogleCallbackRouteImport.update({
    id: '/api/auth/account/google/callback',
    path: '/api/auth/account/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthFirstPasskeyGoogleCallbackRoute =
  ApiAuthFirstPasskeyGoogleCallbackRouteImport.update({
    id: '/api/auth/first-passkey/google/callback',
    path: '/api/auth/first-passkey/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/auth/magic/confirm': typeof AuthMagicConfirmRoute
  '/auth/magic/consume': typeof AuthMagicConsumeRoute
  '/auth/magic/enroll': typeof AuthMagicEnrollRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/account/google/callback': typeof ApiAuthAccountGoogleCallbackRoute
  '/api/auth/first-passkey/google/callback': typeof ApiAuthFirstPasskeyGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/auth/magic/confirm': typeof AuthMagicConfirmRoute
  '/auth/magic/consume': typeof AuthMagicConsumeRoute
  '/auth/magic/enroll': typeof AuthMagicEnrollRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/account/google/callback': typeof ApiAuthAccountGoogleCallbackRoute
  '/api/auth/first-passkey/google/callback': typeof ApiAuthFirstPasskeyGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/auth/magic/confirm': typeof AuthMagicConfirmRoute
  '/auth/magic/consume': typeof AuthMagicConsumeRoute
  '/auth/magic/enroll': typeof AuthMagicEnrollRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/account/google/callback': typeof ApiAuthAccountGoogleCallbackRoute
  '/api/auth/first-passkey/google/callback': typeof ApiAuthFirstPasskeyGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/workspace'
    | '/health/live'
    | '/health/ready'
    | '/auth/magic/confirm'
    | '/auth/magic/consume'
    | '/auth/magic/enroll'
    | '/api/auth/callback/google'
    | '/api/auth/account/google/callback'
    | '/api/auth/first-passkey/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/workspace'
    | '/health/live'
    | '/health/ready'
    | '/auth/magic/confirm'
    | '/auth/magic/consume'
    | '/auth/magic/enroll'
    | '/api/auth/callback/google'
    | '/api/auth/account/google/callback'
    | '/api/auth/first-passkey/google/callback'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/workspace'
    | '/health/live'
    | '/health/ready'
    | '/auth/magic/confirm'
    | '/auth/magic/consume'
    | '/auth/magic/enroll'
    | '/api/auth/callback/google'
    | '/api/auth/account/google/callback'
    | '/api/auth/first-passkey/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  WorkspaceRoute: typeof WorkspaceRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  AuthMagicConfirmRoute: typeof AuthMagicConfirmRoute
  AuthMagicConsumeRoute: typeof AuthMagicConsumeRoute
  AuthMagicEnrollRoute: typeof AuthMagicEnrollRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAuthAccountGoogleCallbackRoute: typeof ApiAuthAccountGoogleCallbackRoute
  ApiAuthFirstPasskeyGoogleCallbackRoute: typeof ApiAuthFirstPasskeyGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic/confirm': {
      id: '/auth/magic/confirm'
      path: '/auth/magic/confirm'
      fullPath: '/auth/magic/confirm'
      preLoaderRoute: typeof AuthMagicConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic/consume': {
      id: '/auth/magic/consume'
      path: '/auth/magic/consume'
      fullPath: '/auth/magic/consume'
      preLoaderRoute: typeof AuthMagicConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic/enroll': {
      id: '/auth/magic/enroll'
      path: '/auth/magic/enroll'
      fullPath: '/auth/magic/enroll'
      preLoaderRoute: typeof AuthMagicEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/account/google/callback': {
      id: '/api/auth/account/google/callback'
      path: '/api/auth/account/google/callback'
      fullPath: '/api/auth/account/google/callback'
      preLoaderRoute: typeof ApiAuthAccountGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/first-passkey/google/callback': {
      id: '/api/auth/first-passkey/google/callback'
      path: '/api/auth/first-passkey/google/callback'
      fullPath: '/api/auth/first-passkey/google/callback'
      preLoaderRoute: typeof ApiAuthFirstPasskeyGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  WorkspaceRoute: WorkspaceRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  AuthMagicConfirmRoute: AuthMagicConfirmRoute,
  AuthMagicConsumeRoute: AuthMagicConsumeRoute,
  AuthMagicEnrollRoute: AuthMagicEnrollRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAuthAccountGoogleCallbackRoute: ApiAuthAccountGoogleCallbackRoute,
  ApiAuthFirstPasskeyGoogleCallbackRoute:
    ApiAuthFirstPasskeyGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
